version: '3.8'

services:
  client:
    build: ./client
    container_name: react_app
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build: ./server
    container_name: express_api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env